### ISSUE TITLE
relstorage 1.6.2: zodbpack on oracle db with pack-gc=true gives error

### ISSUE THREAD

**Issue by peterjacobs** [zodb/relstorage#135]
packing the ZODB gives an error when the setting **pack-gc=true** . It works fine when **pack-gc=false**

Relstorage version tested: 1.6.2 on a Plone installation with history preserving ZODB
cx-oracle version tested: cx_Oracle-5.2-py2.7-linux-x86_64

database: Oracle11

```
bin/zodbpack bin/zodbpack.cfg 
2016-09-30 12:21:46,519 [zodbpack] INFO Opening storage (RelStorageFactory)...
2016-09-30 12:21:46,681 [zodbpack] INFO Packing storage (RelStorageFactory).
2016-09-30 12:21:46,778 [relstorage] INFO pack: analyzing transactions committed Thu Sep 29 14:25:48 2016 or before
2016-09-30 12:21:46,810 [relstorage.adapters.packundo] INFO pre_pack: start with gc enabled
2016-09-30 12:21:46,937 [relstorage.adapters.packundo] INFO pre_pack: analyzing references from objects in 1738 new transaction(s)
2016-09-30 12:21:47,263 [relstorage.adapters.packundo] ERROR pre_pack: failed
Traceback (most recent call last):
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 495, in pre_pack
    conn, cursor, pack_tid, get_references)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 589, in _pre_pack_with_gc
    self.fill_object_refs(conn, cursor, get_references)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 392, in fill_object_refs
    self._add_refs_for_tid(cursor, tid, get_references)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 433, in _add_refs_for_tid
    state = state.read()
ProgrammingError: LOB variable no longer valid after subsequent fetch
Traceback (most recent call last):
  File "bin/zodbpack", line 332, in <module>
    sys.exit(relstorage.zodbpack.main())
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/zodbpack.py", line 81, in main
    storage.pack(t, ZODB.serialize.referencesf)
  File "/demo/eggs/perfmetrics-2.0-py2.7.egg/perfmetrics/__init__.py", line 133, in call_with_metric
    return f(*args, **kw)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/storage.py", line 1181, in pack
    adapter.packundo.pre_pack(tid_int, get_references)
  File "/demo/eggs/perfmetrics-2.0-py2.7.egg/perfmetrics/__init__.py", line 133, in call_with_metric
    return f(*args, **kw)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 495, in pre_pack
    conn, cursor, pack_tid, get_references)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 589, in _pre_pack_with_gc
    self.fill_object_refs(conn, cursor, get_references)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 392, in fill_object_refs
    self._add_refs_for_tid(cursor, tid, get_references)
  File "/demo/eggs/RelStorage-1.6.2-py2.7.egg/relstorage/adapters/packundo.py", line 433, in _add_refs_for_tid
    state = state.read()
cx_Oracle.ProgrammingError: LOB variable no longer valid after subsequent fetch
```
zodbpack.cfg
```
<relstorage>
  pack-gc true
  <oracle>
    dsn  (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = host)(PORT = 1234)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = PLONE)))
    user plone
    password pwd
  </oracle>
</relstorage>
```

**Comment by jamadden** [comment]
Can you try changing line 430 of packundo.py to use `self._fetchmany`?

I don't have my Oracle VM spun up now, and it's very slow---but apparently this line isn't covered during the unit tests or I would have seen it before (I promise I tested the fix before releasing it in 2.0bX)!

What version of cx_Oracle are you using? I tested with the latest. Perhaps that could be it.

(Actually, I don't know why it wouldn't be safe to turn all uses of the bare `fetchmany` into `self._fetchmany`.)

**Comment by peterjacobs** [comment]
Yes, that fixes it! (together with a fix in OracleHistoryPreservingPackUndo to give it the same behaviour as OracleHistoryFreePackUndo)

```
diff packundo.py.dist packundo.py
430c430
<         for from_oid, state in fetchmany(cursor):
---
>         for from_oid, state in self._fetchmany(cursor):
916a917,918
> 
>     _fetchmany = _oracle_fetchmany
```

**Comment by jamadden** [comment]
Cool, I'll make that change.

Any news on the cx_Oracle version? I'm trying to figure out why I didn't produce this locally in testing.

**Comment by peterjacobs** [comment]
it is in the original description: cx_Oracle-5.2-py2.7-linux-x86_64

**Comment by jamadden** [comment]
Sorry, I completely missed that line. It's early here 😄

**Comment by peterjacobs** [comment]
thanks for the quick fixes!

**Comment by peterjacobs** [comment]
tested with cx_Oracle-5.2.1-py2.7-linux-x86_64.egg
same error
