### ISSUE TITLE
Uncaught exception when shutting down server

### ISSUE THREAD

**Issue by neilferreira** [zodb/relstorage#14]
Hi all

I'm getting an error when shutting down my server in my development environment.
Plone 4.3.3
RelStorage = 1.5.1

sauna and get the same issue when CTRL + C'ing the insance.
```
[instance]
<= instance_base
recipe = plone.recipe.zope2instance
http-address = 8080
blob-dir ${buildout:var-dir}/blobstorage
dsn dbname = ${buildout:database-name} host=${buildout:database-host} user=${buildout:database-user}
```

```
^C2014-06-17 14:15:21 INFO SignalHandler Caught signal SIGINT
2014-06-17 14:15:21 INFO Z2 Shutting down
Traceback (most recent call last):
  File "/home/neilf/development/website/website-website.wa.gov.au-v2/parts/instance/bin/interpreter", line 328, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/neilf/development/website/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/neilf/development/website/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 26, in run
    starter.run()
  File "/home/neilf/development/website/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 108, in run
    self.shutdown()
  File "/home/neilf/development/website/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 113, in shutdown
    db.close()
  File "/home/neilf/development/website/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 624, in close
    @self._connectionMap
  File "/home/neilf/development/website/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 506, in _connectionMap
    self.pool.map(f)
  File "/home/neilf/development/website/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 206, in map
    self.all.map(f)
  File "/home/neilf/development/website/buildout-cache/eggs/transaction-1.1.1-py2.7.egg/transaction/weakset.py", line 58, in map
    f(elt)
  File "/home/neilf/development/website/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 628, in _
    c._release_resources()
  File "/home/neilf/development/website/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 1075, in _release_resources
    c._storage.release()
AttributeError: 'NoneType' object has no attribute 'release'
```

**Comment by neilferreira** [comment]
Just coming back to this now.  I noticed my original thread mentioned this error only occured when Plone was starting up.  I now can't get Plone to start with sauna/relstorage.

```
2016-01-18 16:42:31 INFO ZServer HTTP server started at Mon Jan 18 16:42:31 2016
	Hostname: 0.0.0.0
	Port: 8080
2016-01-18 16:42:32 INFO Products.PloneFormGen gpg_subprocess initialized, using /usr/bin/gpg
2016-01-18 16:42:32 WARNING ZODB.blob (11709) Blob dir /home/neil/development/site/var/blobstorage/ has insecure mode setting
2016-01-18 16:42:36 WARNING Init Class plone.app.tiles.browser.add.DefaultAddView has a security declaration for nonexistent method 'browserDefault'
2016-01-18 16:42:36 WARNING Init Class plone.app.tiles.browser.add.DefaultAddView has a security declaration for nonexistent method 'publishTraverse'
2016-01-18 16:42:36 WARNING Init Class plone.app.tiles.browser.edit.DefaultEditView has a security declaration for nonexistent method 'browserDefault'
2016-01-18 16:42:36 WARNING Init Class plone.app.tiles.browser.edit.DefaultEditView has a security declaration for nonexistent method 'publishTraverse'
2016-01-18 16:42:36 INFO Products.LongRequestLogger.patch patching ZPublisher.Publish.publish_module_standard
2016-01-18 16:42:36 INFO PloneFormGen Patching plone.app.portlets ColumnPortletManagerRenderer to not catch Retry exceptions
2016-01-18 16:42:36 INFO Zope Ready to handle requests
2016-01-18 16:42:36 INFO sauna.reload.parent Starting file monitor on /home/neil/development/site/src
2016-01-18 16:42:37 INFO sauna.reload.parent We saved at least 6.7190079689 seconds from boot up time
2016-01-18 16:42:37 INFO sauna.reload.parent Overview available at http://127.0.0.1:8080/@@saunareload
Traceback (most recent call last):
  File "/home/neil/development/site/parts/instance/bin/interpreter", line 375, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/neil/development/site/buildout-eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/neil/development/site/buildout-eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 24, in run
    starter.shutdown()
  File "/home/neil/development/site/buildout-eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 113, in shutdown
    db.close()
  File "/home/neil/development/site/buildout-eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 624, in close
    @self._connectionMap
  File "/home/neil/development/site/buildout-eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 506, in _connectionMap
    self.pool.map(f)
  File "/home/neil/development/site/buildout-eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 206, in map
    self.all.map(f)
  File "/home/neil/development/site/buildout-eggs/transaction-1.1.1-py2.7.egg/transaction/weakset.py", line 58, in map
    f(elt)
  File "/home/neil/development/site/buildout-eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/DB.py", line 628, in _
    c._release_resources()
  File "/home/neil/development/site/buildout-eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 1075, in _release_resources
    c._storage.release()
AttributeError: 'NoneType' object has no attribute 'release'
neil@neil-iMac:~/development/site$ 
```

Any ideas?

**Comment by neilferreira** [comment]
I just read my initial post again.  I did mention this at the time, you are unable to start Plone when sauna and relstorage are both installed.

You can run Plone fine if you don't set the RELOAD_PATH for Sauna to load, but when the instance shuts down you get the same error.

**Comment by do3cc** [comment]
This is a ZODB bug

**Comment by seanupton** [comment]
> This is a ZODB bug

@do3cc well, the connection's storage is None.  That's Zope2's doing (see my comment above for link to commit). You could have ZODB test that the connection._storage is not None before attempting release()?  This could get fixed in either ZODB or in Zope2.  Might be a good idea to poll the ZODB list (on Google Groups) to see which makes most sense?

**Comment by do3cc** [comment]
Hi Sean,

Did you have a look at the linked bug in ZODB? I've created a PR there which does that. What I forgot to write there was my analysis why this happens with relstorage and not with the filestorage. I'll ad that when I also adjust the changelog entry.

Von meinem iPhone gesendet

Am 17.03.2016 um 03:23 schrieb Sean Upton <notifications@github.com<mailto:notifications@github.com>>:


This is a ZODB bug

@do3cc<https://github.com/do3cc> well, the connection's storage is None. That's Zope2's doing (see my comment above for link to commit). You could have ZODB test that the connection._storage is not None before attempting release()? This could get fixed in either ZODB or in Zope2. Might be a good idea to poll the ZODB list (on Google Groups) to see which makes most sense?

-
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/zodb/relstorage/issues/14#issuecomment-197658177>

________________________________________________________ The contents of this e-mail and any attachments are confidential to the intended recipient. They may not be disclosed to or used by or copied in any way by anyone other than the intended recipient. If this e-mail is received in error, please immediately notify the sender and delete the e-mail and attached documents. Please note that neither the sender nor the sender's company accept any responsibility for viruses and it is your responsibility to scan or otherwise check this e-mail and any attachments.

**Comment by jamadden** [comment]
This was fixed with https://github.com/zopefoundation/ZODB/pull/46
