### ISSUE TITLE
demostorage & relstorage does not reload on disconn

### ISSUE THREAD

**Issue by runyaga** [zodb/relstorage#15]
Stacking demostrage with relstorage does not reconnect when encountering disconnected_exceptions

zope.conf:
```
<zodb_db main>
    # Main database
    cache-size 100000
    <demostorage>
    %import relstorage
    <relstorage base>
        commit-lock-timeout 240
        blob-dir /opt/plone/responsive/var/blobcache
        blob-cache-size 10gb
        shared-blob-dir false
        <mysql>
            passwd secretpassword
            db zodb
            host localhost
            user zope
            port 3306
        </mysql>
    </relstorage>
    # Blob-enabled FileStorage database
    <blobstorage changes>
      blob-dir /opt/plone/responsive/var/demostorage/blobstorage
      # FileStorage database
      <filestorage>
        path /opt/plone/responsive/var/demostorage/Data.fs
      </filestorage>
    </blobstorage>
    </demostorage>
    mount-point /
</zodb_db>
```

traceback:
```
2014-05-27T09:47:06 ERROR ZODB.Connection Couldn't load state for 0x1e7708
Traceback (most recent call last):
  File "/opt/plone/buildout/eggs/ZODB3-3.10.3-py2.6-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/opt/plone/buildout/eggs/ZODB3-3.10.3-py2.6-linux-x86_64.egg/ZODB/Connection.py", line 901, in _setstate
    p, serial = self._storage.load(obj._p_oid, '')
  File "/opt/plone/buildout/eggs/ZODB3-3.10.3-py2.6-linux-x86_64.egg/ZODB/DemoStorage.py", line 159, in load
    return self.base.load(oid, version)
  File "/opt/plone/buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/storage.py", line 457, in load
    state, tid_int = cache.load(cursor, oid_int)
  File "/opt/plone/buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/cache.py", line 279, in load
    state, tid_int = self.adapter.mover.load_current(cursor, oid_int)
  File "/opt/plone/buildout/eggs/RelStorage-1.5.1-py2.6.egg/relstorage/adapters/mover.py", line 130, in mysql_load_current
    cursor.execute(stmt, (oid,))
  File "/opt/plone/buildout/eggs/MySQL_python-1.2.3-py2.6-linux-x86_64.egg/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/opt/plone/buildout/eggs/MySQL_python-1.2.3-py2.6-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by jamadden** [comment]
I don't believe DemoStorage has anything to do with it (other than perhaps changing the prevalence or timing).

I believe this is deliberate.

RelStorage does not catch and recover from the disconnected exceptions *except* at particular points when it is safe to do so from a transactional standpoint. This is because the RDBMS (MySQL) connection contains state that RelStorage relies on to properly implement transactional consistency. Think of a RDBMS connection as a point in time. If it started a transaction at one point in time, but then load() switched to a different connection, the transaction would be using data from two different times! Not very transactional.
