### ISSUE TITLE
Error on flush_invalidations

### ISSUE THREAD

**Issue by cdw9** [zodb/relstorage#195]
Plone 5.1rc2
relstorage 1.5.1 - 1.6.3
ZODB 5.1.1

I may not have the correct combinations of versions (I tried a few), but I kept getting the error below when running buildout:
```
Traceback (most recent call last):
  File "/Users/chrissy/projects/cnm/cnm-plone5/parts/instance/bin/interpreter", line 352, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/Users/chrissy/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 51, in app
    startup()
  File "/Users/chrissy/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/Users/chrissy/.buildout/eggs/Zope2-2.13.26-py2.7.egg/Zope2/App/startup.py", line 125, in startup
    DB, 'Application', OFS.Application.Application, ()
  File "/Users/chrissy/.buildout/eggs/Zope2-2.13.26-py2.7.egg/App/ZApplication.py", line 29, in __init__
    conn=db.open()
  File "/Users/chrissy/.buildout/eggs/ZODB-5.1.1-py2.7.egg/ZODB/DB.py", line 772, in open
    result.open(transaction_manager)
  File "/Users/chrissy/.buildout/eggs/ZODB-5.1.1-py2.7.egg/ZODB/Connection.py", line 904, in open
    self.newTransaction(None, False)
  File "/Users/chrissy/.buildout/eggs/RelStorage-1.6.3-py2.7.egg/relstorage/__init__.py", line 50, in _storage_sync
    self._flush_invalidations()
AttributeError: 'Connection' object has no attribute '_flush_invalidations'
```

**Comment by cdw9** [comment]
I was able to get around this by replacing `self._flush_invalidations()` in `__init__.py` with this:

```
invalidated = self._storage.poll_invalidations()
if invalidated is None:
    # special value: the transaction is so old that
    # we need to flush the whole cache.
    invalidated = self._cache.cache_data.copy()
self._cache.invalidate(invalidated)
```

I'm just not sure if this is the actual fix. If so, I can put in a PR.

**Comment by jamadden** [comment]
If you're using ZODB 5, you need RelStorage 2.0.0b3 or newer (I recommend 2.1a2). RelStorage 1.x is only compatible with older ZODB releases.
