### ISSUE TITLE
Blobs are sometimes empty

### ISSUE THREAD

**Issue by jamadden** [zodb/relstorage#219]
Sometimes the PostgreSQLUnsharedWithHistoryBlobTests group of tests fails in `blob_cache.tests`, producing `bad data; expected 42 got b''`.

This is happening with a small blob under Python 3.7 on macOS. I added debug logging to the postgres mover's `download_blob` method: write after we write the first blob chunk using the native "export" method of the blob, I open the file, read the data, and print the contents:
```
 Wrote 200 to /private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/testtklv0kuc/blobs/9/3.03cf99c00867c677.blob.tmp b'424...'`
```
Shortly after that, we rename the file to drop the `.tmp` suffix. Then the blob test tries to open and read the blob by that new name:
```
bad data; expected 42 got b'' <_io.FileIO name='/private/var/folders/y5/x7pvzk651c3dqkllbxd1jd280000gn/T/testtklv0kuc/blobs/9/3.03cf99c00867c677.blob' mode='rb' closefd=True>
```

I have no indication that the blob file was overwritten at any point in between.

**Comment by jamadden** [comment]
This doesn't just affect postgres. This is a race condition with the background thread (implemented in ZEO) that keeps a local blob cache in its size range. I changed the logging in `ZEO.ClientStorage._check_blob_cache_size` to note when it is removing the file and that turns out to be the cause:
```
Wrote 200 to //blobs/8/6.03cf99d1530e4277.blob.tmp b'7474747474747
ZEO: Removing committed blob file //blobs/8/6.03cf99d1530e4277.blob
bad data; expected 74 got b'' <_io.BufferedReader name='//blobs/8/6.03cf99d1530e4277.blob'>
```

**Comment by jamadden** [comment]
RelStorage's `blobhelper.py` defines `openCommittedFile` like this (logging added to demonstrate):
```python
    def openCommittedBlobFile(self, cursor, oid, serial, blob=None):
        blob_filename = self.loadBlob(cursor, oid, serial)
        e = None
        try:
            if blob is None:
                return open(blob_filename, 'rb')
            return ZODB.blob.BlobFile(blob_filename, 'r', blob)
        except IOError:
            # The file got removed while we were opening.
            # Fall through and try again with the protection of the lock.
            e = sys.exc_info()[1]
        finally:
            print("Opened committed blob file", blob_filename, e, threading.current_thread())
        lock = _lock_blob(blob_filename)
        try:
            blob_filename = self.fshelper.getBlobFilename(oid, serial)
            if not os.path.exists(blob_filename):
                ...
                self.download_blob(cursor, oid, serial, blob_filename)
```

I observe this sequence of calls to create the problem:
```
Opened committed blob file //0/9.03d09ddacda3db00.blob None  <Thread(Thread-149, started daemon 123145487159296)>
Removed //0/9.03d09ddacda3db00.blob
Closed //data.blobs/0/9.03d09ddacda3db00.blob Empty? 0 <Thread(Thread-149, started daemon 123145487159296)>
```

(I originally had a much more complicated example, because I was using `blob.committed()` in my logging. It turns out that `blob.committed()` will go-ahead and re-download the file if needed, making it much harder to isolate the sequence of calls here.)

1. Thread 149 opens the file. This succeeds without raising an error, so we return that opened file.
2. Meanwhile, the background thread removes the file.
3. Thread 149 reads the file, and gets 0 bytes. Boom!

(There's no indication that any other thread was attempting to access this file at this time.)

That's not supposed to happen. On POSIX, an open file is supposed to still be readable. It turns out to be fairly easy to produce this race condition with an independent script.

```python
from io import FileIO as file
import os
import threading

class BlobFile(file):
    pass

data = '10' * 100
data = data.encode('ascii')
for i in range(1000):
    with open('/tmp/foo', 'wb') as f:
        f.write(data)
    t = threading.Thread(target=os.remove, args=('/tmp/foo',))
    t.start()
    f = BlobFile('/tmp/foo', 'rb')
    t.join()
    read = f.read()
    f.close()
    assert read == data, (read, f, i)
```

On our first iteration, we succeeded in opening the file without producing a `FileNotFoundError`, but we can't read it:
```console
Traceback (most recent call last):
  File "/tmp/test.py", line 19, in <module>
    assert read == data, (read, f, i)
AssertionError: (b'', <_io.FileIO [closed]>, 0)
```

Here's another try; we get the IO error we're expecting if the two threads are racing and the removal wins:
```console
$ python /tmp/test.py
Traceback (most recent call last):
  File "/tmp/test.py", line 15, in <module>
    f = BlobFile('/tmp/foo', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/foo'
```

Under Python 2.7, I've *only* been able to produce the expected `IOError`, but I can get the `AssertionError` on Python 3.4 and up. So it would seem that `io.FileIO` and `open()` are somehow not as nearly atomic as we would expect them to be on Python 3, at least on this platform.

Here's the sequence of system calls, as reported by dtruss:
```
70592/0xbda81f:  write(0x3, "...\002r8\0", 0xC8)	 = 200 0
70592/0xbda81f:  close(0x3)		 = 0 0
70592/0xbda81f:  bsdthread_create(0x1045FC933, 0x7FC5F0C20860, 0x700008F48000)		 = 150241280 0
70592/0xbda820:  thread_selfid(0x0, 0x0, 0x0)		 = 12429344 0
70592/0xbda820:  psynch_cvsignal(0x7FC5F0C07E38, 0x100, 0x0)		 = 257 0
70592/0xbda81f:  psynch_cvwait(0x7FC5F0C07E38, 0x100000100, 0x0)		 = 0 0
```
OK, we wrote and closed the file, then created the thread. 
```
70592/0xbda81f:  open("/tmp/foo\0", 0x1000000, 0x1B6)		 = 3 0
70592/0xbda81f:  fstat64(0x3, 0x7FFEEB6E2A08, 0x0)		 = 0 0
70592/0xbda81f:  ioctl(0x3, 0x4004667A, 0x7FFEEB6E2A64)		 = -1 Err#25
70592/0xbda81f:  ioctl(0x3, 0x40487413, 0x7FFEEB6E2A68)		 = -1 Err#25
70592/0xbda81f:  lseek(0x3, 0x0, 0x1)		 = 0 0
70592/0xbda820:  unlink("/tmp/foo\0", 0x0, 0x0)		 = 0 0
70592/0xbda820:  psynch_cvsignal(0x7FC5F0E00E58, 0x100, 0x0)		 = 257 0
70592/0xbda81f:  psynch_cvwait(0x7FC5F0E00E58, 0x100000100, 0x0)		 = 0 0
70592/0xbda820:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
```
We opened the file, did some Python-file-object stuff (the ioctls failed with "ENOTTY"), and the thread deleted it. Then we joined the thread.

```
70592/0xbda81f:  lseek(0x3, 0x0, 0x1)		 = 0 0
70592/0xbda81f:  fstat64(0x3, 0x7FFEEB6E2BE0, 0x0)		 = 0 0
70592/0xbda81f:  read(0x3, "\0", 0x2000)		 = 0 0
70592/0xbda81f:  close(0x3)		 = 0 0
```
Hmm. We seek to the beginning of the file (0x1 is SEEK_CUR, with an offset of 0 bytes: don't change anything). We stat the file (for some reason). And then we read from the file, and get back the C empty string. All of that succeeds, but obviously, the file is empty.

If I use the low-level `os.fdopen()`, it either works or it fails with the expected IOError. So it appears something in the stat, ioctl or lseek syscalls is breaking things.

This is Python 2, where it works (if I modify the background thread to wait until I open the file before unlinking):
```
thread_selfid(0x0, 0x0, 0x0)		 = 12472682 0
psynch_mutexwait(0x7FAA8B62C768, 0x102, 0x0)		 = 259 0
psynch_cvsignal(0x7FAA8B62C738, 0x100, 0x0)		 = 257 0
psynch_cvwait(0x7FAA8B62C738, 0x100000100, 0x0)		 = 0 0
psynch_cvsignal(0x7FAA8B711F88, 0x100, 0x0)		 = 257 0
psynch_cvwait(0x7FAA8B711F88, 0x100000100, 0x0)		 = 0 0
open_nocancel("/tmp/foo\0", 0x0, 0x1B6)		 = 3 0
fstat64(0x3, 0x7FFEED2EAF18, 0x0)		 = 0 0
select(0x0, 0x0, 0x0, 0x0, 0x70000099B368)		 = 0 0
unlink("/tmp/foo\0", 0x0, 0x0)		 = 0 0
psynch_cvsignal(0x7FAA8B50D2A8, 0x100, 0x0)		 = 257 0
psynch_cvwait(0x7FAA8B50D2A8, 0x100000100, 0x0)		 = 0 0
__disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
fstat64(0x3, 0x7FFEED2EB030, 0x0)		 = 0 0
lseek(0x3, 0x0, 0x1)		 = 0 0
lseek(0x3, 0x0, 0x1)		 = 0 0
fstat64(0x3, 0x7FFEED2EAF18, 0x0)		 = 0 0
read_nocancel(0x3, "1111111111\0", 0x1000)		 = 10 0
```

A couple of seeks and fstats after we're unlinked, like on Python 3. The flags to `open` are different (Python 3 passes O_CLOEXEC, Python 2 passes nothing). I *think* the `select` might be the rough equivalent in Py2 of Py3's failed ioctls? Python 2 uses a smaller buffer...hmm?

If I change the line that opens the file to specify `buffering=0xB`, I can get Python 3 to work....sometimes. When it uses my buffer size, it does what it's supposed to:
```
86435/0xbebbd1:  open("/tmp/foo\0", 0x1000000, 0x1B6)		 = 3 0
86435/0xbebbd3:  unlink("/tmp/foo\0", 0x0, 0x0)		 = 0 0
86435/0xbebbd1:  fstat64(0x3, 0x7FFEE1426A08, 0x0)		 = 0 0
86435/0xbebbd1:  gettimeofday(0x7FFEE14268F0, 0x0, 0x0)		 = 0 0
86435/0xbebbd3:  psynch_mutexwait(0x10E9EAEA8, 0x102, 0x0)		 = 259 0
86435/0xbebbd3:  psynch_cvsignal(0x10E9EAE78, 0x100, 0x0)		 = 257 0
86435/0xbebbd1:  psynch_cvwait(0x10E9EAE78, 0x100000100, 0x0)		 = 0 0
86435/0xbebbd3:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
86435/0xbebbd1:  ioctl(0x3, 0x4004667A, 0x7FFEE1426A64)		 = -1 Err#25
86435/0xbebbd1:  ioctl(0x3, 0x40487413, 0x7FFEE1426A68)		 = -1 Err#25
86435/0xbebbd1:  lseek(0x3, 0x0, 0x1)		 = 0 0
86435/0xbebbd1:  lseek(0x3, 0x0, 0x1)		 = 0 0
86435/0xbebbd1:  fstat64(0x3, 0x7FFEE1426BE0, 0x0)		 = 0 0
86435/0xbebbd1:  read(0x3, "1111111111\0", 0xB)		 = 10 0
```

But it doesn't always use my buffer size. Sometimes it goes back to the default. Here's an AssertionError where it (for some reason) used the default buffer size. Note that it also appeared to unlink the file before opening it:
```
86882/0xbec60d:  bsdthread_create(0x108AEF933, 0x7FAC9A637AF0, 0x700007833000)		 = 126038016 0
86882/0xbec60f:  thread_selfid(0x0, 0x0, 0x0)		 = 12502543 0
86882/0xbec60f:  psynch_cvsignal(0x7FAC9A60BCF8, 0x100, 0x0)		 = 257 0
86882/0xbec60d:  psynch_cvwait(0x7FAC9A60BCF8, 0x100000100, 0x0)		 = 0 0
86882/0xbec60f:  unlink("/tmp/foo\0", 0x0, 0x0)		 = 0 0
86882/0xbec60d:  open("/tmp/foo\0", 0x1000000, 0x1B6)		 = 3 0
86882/0xbec60d:  fstat64(0x3, 0x7FFEE71F0A08, 0x0)		 = 0 0
86882/0xbec60f:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
86882/0xbec60d:  ioctl(0x3, 0x4004667A, 0x7FFEE71F0A64)		 = -1 Err#25
86882/0xbec60d:  ioctl(0x3, 0x40487413, 0x7FFEE71F0A68)		 = -1 Err#25
86882/0xbec60d:  lseek(0x3, 0x0, 0x1)		 = 0 0
86882/0xbec60d:  lseek(0x3, 0x0, 0x1)		 = 0 0
86882/0xbec60d:  fstat64(0x3, 0x7FFEE71F0BE0, 0x0)		 = 0 0
86882/0xbec60d:  read(0x3, "\003\0", 0x2000)		 = 0 0
```

But here's one where we got the AssertionError, but had opened before we unlinked; again, it's back to using the wrong buffer size:
```
87342/0xbecfe5:  thread_selfid(0x0, 0x0, 0x0)		 = 12505061 0
87342/0xbecfe5:  gettimeofday(0x70000FE2DDB0, 0x0, 0x0)		 = 0 0
87342/0xbecfe4:  psynch_mutexwait(0x109095EA8, 0x102, 0x0)		 = 259 0
87342/0xbecfe4:  psynch_cvsignal(0x109095E78, 0x100, 0x0)		 = 257 0
87342/0xbecfe5:  psynch_cvwait(0x109095E78, 0x100000100, 0x0)		 = 0 0
87342/0xbecfe5:  psynch_cvsignal(0x7FE14F412CB8, 0x100, 0x0)		 = 257 0
87342/0xbecfe4:  psynch_cvwait(0x7FE14F412CB8, 0x100000100, 0x0)		 = 0 0
87342/0xbecfe4:  open("/tmp/foo\0", 0x1000000, 0x1B6)		 = 3 0
87342/0xbecfe4:  fstat64(0x3, 0x7FFEE6D7DA08, 0x0)		 = 0 0
87342/0xbecfe4:  ioctl(0x3, 0x4004667A, 0x7FFEE6D7DA64)		 = -1 Err#25
87342/0xbecfe4:  ioctl(0x3, 0x40487413, 0x7FFEE6D7DA68)		 = -1 Err#25
87342/0xbecfe4:  lseek(0x3, 0x0, 0x1)		 = 0 0
87342/0xbecfe5:  unlink("/tmp/foo\0", 0x0, 0x0)		 = 0 0
87342/0xbecfe5:  psynch_cvsignal(0x7FE14F422ED8, 0x100, 0x0)		 = 257 0
87342/0xbecfe4:  psynch_cvwait(0x7FE14F422ED8, 0x100000100, 0x0)		 = 0 0
87342/0xbecfe5:  __disable_threadsignal(0x1, 0x0, 0x0)		 = 0 0
87342/0xbecfe4:  lseek(0x3, 0x0, 0x1)		 = 0 0
87342/0xbecfe4:  fstat64(0x3, 0x7FFEE6D7DBE0, 0x0)		 = 0 0
87342/0xbecfe4:  read(0x3, "\0", 0x2000)		 = 0 0
```

I suspect the buffer is a symptom, not the cause.

**Comment by jamadden** [comment]
Ahh, code in `Modules/_io/fileio.c` chooses a buffer for read() based on the result of `fstat()`:
```C
    fstat_result = _Py_fstat_noraise(self->fd, &status);
    Py_END_ALLOW_THREADS

    if (fstat_result == 0)
        end = status.st_size;
    else
        end = (Py_off_t)-1;

    if (end > 0 && end >= pos && pos >= 0 && end - pos < PY_SSIZE_T_MAX) {
        /* This is probably a real file, so we try to allocate a
           buffer one byte larger than the rest of the file.  If the
           calculation is right then we should get EOF without having
           to enlarge the buffer. */
        bufsize = (size_t)(end - pos + 1);
    } else {
        bufsize = SMALLCHUNK;
    }
```
`SMALLCHUNK` happens to be 0x2000, and `end` is `off_t`, a signed integer. So if the stat call doesn't return successfully (and it does), or if it returns a size of 0, we default to using 0x2000 bytes.

Sure enough, if I add a `os.fstat` call to the test program, if it returns a valid size, the read succeeds, otherwise we get the AssertionError:
```
94585
Thread: Done removing
Main: os.stat_result(st_mode=32768, st_ino=0, st_dev=16777221, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=0, st_mtime=0, st_ctime=0)
Traceback (most recent call last):
  File "/tmp/test.py", line 33, in <module>
    assert read == data, (read, f, i)
AssertionError: (b'', <_io.BufferedReader name='/tmp/foo'>, 0)
```
```
95240
Done removing
os.stat_result(st_mode=33188, st_ino=8721622679, st_dev=16777221, st_nlink=0, st_uid=501, st_gid=0, st_size=10, st_atime=1561417490, st_mtime=1561417490, st_ctime=1561417490)
```

**Comment by jamadden** [comment]
Using `time.perf_counter_ns()` to try to express when exactly various syscalls return to the Python level, we note that it appears to be the *interleaving* that causes the issues. One may think it related to the GIL and a Time-of-check-vs-time-of-use for constructing the file object, but if that's the case (1) why does the `open` syscall respond with a valid file-descriptor and (2) why does the `fstat` syscall respond with a non-error instead of EBADF?

```
44018542 Begin removing /tmp/foo # In the thread, GIL drops on next line
44057520 Begin open # Somewhere in here the GIL drops
44214885 End open # Re-acquired the GIL; now we join the thread and release the GIL
45637909 Done removing /tmp/foo # Back in the thread
45742355 os.stat_result(st_mode=32768, st_ino=0, st_dev=16777221, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=0, st_mtime=0, st_ctime=0) # Back in main
Traceback (most recent call last):
  File "/tmp/test.py", line 44, in <module>
    assert read == data, (read, f, i)
AssertionError: (b'', <_io.BufferedReader name='/tmp/foo'>, 0)
```
