### ISSUE TITLE
Py MySQL Connector/Python broken

### ISSUE THREAD

**Issue by jamadden** [zodb/relstorage#228]
On both Python 2 and Python 3. Due to the confusing name of the driver before the work for #224, we were only testing the C extension.

Example [Python 2 error](https://travis-ci.org/zodb/relstorage/jobs/531775075#L970) (Python 3 produces the same thing with `int`):
```Python traceback
  File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 1439, in loadBlob
    return self.blobhelper.loadBlob(cursor, oid, serial)
  File "/home/travis/build/zodb/relstorage/src/relstorage/blobhelper.py", line 140, in loadBlob
    self.download_blob(cursor, oid, serial, blob_filename)
  File "/home/travis/build/zodb/relstorage/src/relstorage/blobhelper.py", line 89, in download_blob
    cursor, u64(oid), u64(serial), tmp_fn)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/perfmetrics/__init__.py", line 127, in call_with_metric
    return f(*args, **kw)
  File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/mysql/mover.py", line 174, in download_blob
    f.write(chunk)
TypeError: argument 1 must be string or buffer, not long
```

We also get some failed assertion errors about object states not coming back as `bytes`. [Python 2](https://travis-ci.org/zodb/relstorage/jobs/531775075#L1299):
```Python traceback
Failure in test checkPackBrokenPickle (relstorage.tests.testmysql.MySQLHistoryFreeRelStorageTests_PyMySQLConnectorDriver)
Traceback (most recent call last):
  File "/opt/python/2.7.15/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/travis/build/zodb/relstorage/src/relstorage/tests/reltestbase.py", line 743, in checkPackBrokenPickle
    time.time() + 10000, referencesf)
  File "/opt/python/2.7.15/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
    return f(*args, **kw)
  File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 1321, in pack
    adapter.packundo.pre_pack(tid_int, get_references)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
    return f(*args, **kw)
  File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 1018, in pre_pack
    self._pre_pack_main(conn, cursor, pack_tid, get_references)
  File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 1037m, in _pre_pack_main
    self.fill_object_refs(conn, cursor, get_references)
  File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 918, in fill_object_refs
    self._add_refs_for_oids(cursor, batch, get_references)
  File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 965, in _add_refs_for_oids
    assert isinstance(state, bytes), type(state)
AssertionError: <type 'unicode'>
    80/226 (35.4%)
Failure in test check_checkCurrentSerialInTransaction (relstorage.tests.testmysql.MySQLHistoryFreeRelStorageTests_PyMySQLConnectorDriver)
Traceback (most recent call last):
  File "/opt/python/2.7.15/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/ZODB/tests/BasicStorage.py", line 267, in check_checkCurrentSerialInTransaction
    self._storage, b'\0\0\0\0\0\0\0\xf3')[1])
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/ZODB/utils.py", line 385, in load_current
    r = storage.loadBefore(oid, maxtid)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/perfmetrics/__init__.py", line 127, in call_with_metric
    return f(*args, **kw)
  File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 664, in loadBefore
    assert isinstance(state, bytes), type(state) # XXX Py3 port: state = str(state)
AssertionError: <type 'unicode'>
```

[Python 3](https://travis-ci.org/zodb/relstorage/jobs/531775078#L1708):
```Python traceback
File "/home/travis/build/zodb/relstorage/src/relstorage/tests/blob/testblob.py", line 396, in relstorage.tests.blob.testblob.packing_with_uncommitted_data_undoing
Failed example:
    blob_storage.pack(new_time(), referencesf)
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.7.1/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest relstorage.tests.blob.testblob.packing_with_uncommitted_data_undoing[10]>", line 1, in <module>
        blob_storage.pack(new_time(), referencesf)
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
        return f(*args, **kw)
      File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 1321, in pack
        adapter.packundo.pre_pack(tid_int, get_references)
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
        return f(*args, **kw)
      File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 497, in pre_pack
        conn, cursor, pack_tid, get_references)
      File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 591, in _pre_pack_with_gc
        self.fill_object_refs(conn, cursor, get_references)
      File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 404, in fill_object_refs
        self._add_refs_for_tid(cursor, tid, get_references)
      File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 439, in _add_refs_for_tid
        assert isinstance(state, bytes), type(state) # PY3: used to be str(state)
    AssertionError: <class 'bytearray'>
    11/16 (68.8%)
Failure in test testSimpleBlobRecovery (relstorage.tests.blob.testblob.MySQLUnsharedWithHistory_PyMySQLConnectorDriverRecoveryBlobStorage)
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/opt/python/3.7.1/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/home/travis/build/zodb/relstorage/src/relstorage/tests/blob/testblob.py", line 290, in testSimpleBlobRecovery
    self._dst.copyTransactionsFrom(self._storage)
  File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 1511, in copyTransactionsFrom
    for record in trans:
  File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 1660, in next
    res = Record(self.tid, *params)
  File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 1673, in __init__
    assert isinstance(data, bytes)
AssertionError
```

**Comment by jamadden** [comment]
Also for some reason, we're broken in a different way [on PyPy](https://travis-ci.org/zodb/relstorage/jobs/531775079#L377):
```Python traceback
----------------------------------------------------------------------
File "/home/travis/build/zodb/relstorage/src/relstorage/tests/blob/blob_packing.txt", line 72, in blob_packing.txt
Failed example:
    blob_storage.pack(packtime, referencesf)
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/pypy2.7-7.1.1/lib-python/2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest blob_packing.txt[27]>", line 1, in <module>
        blob_storage.pack(packtime, referencesf)
      File "/home/travis/virtualenv/pypy2.7-7.1.1/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
        return f(*args, **kw)
      File "/home/travis/build/zodb/relstorage/src/relstorage/storage.py", line 1321, in pack
        adapter.packundo.pre_pack(tid_int, get_references)
      File "/home/travis/virtualenv/pypy2.7-7.1.1/site-packages/perfmetrics/__init__.py", line 133, in call_with_metric
        return f(*args, **kw)
      File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/packundo.py", line 521, in pre_pack
        cursor, stmt, {'pack_tid': pack_tid})
      File "/home/travis/build/zodb/relstorage/src/relstorage/adapters/scriptrunner.py", line 55, in run_script_stmt
        cursor.execute(stmt, generic_params)
      File "/home/travis/virtualenv/pypy2.7-7.1.1/site-packages/mysql/connector/cursor.py", line 573, in execute
        "Use multi=True when executing multiple statements")
    InterfaceError: Use multi=True when executing multiple statements
```

**Comment by jamadden** [comment]
Hmm. I reproduce the PyPy problem locally in zodbshootout when using concurrency greater than 1; but when concurrency is 1, it works just fine. Is something being shared that's not supposed to be?

**Comment by jamadden** [comment]
Today I learned that MySQL internally stores its JSON type exactly the same as a BLOB. 

When the MySQL Connector/Python client gets a BLOB (Binary Large Object) value from the server, it first tries to *parse it as JSON*, meaning that a BLOB that you stored `"true"` in you could get back as the constant `True`. Or if you stored the binary value `"2019-01-31"` you will get back a date object, instead of the byte string you're expecting.

**Comment by jamadden** [comment]
Two more *interesting* things:

- The type conversion of bytes-to-objects has a bug when the C connection implementation is in use. If you get back a column value of `0`, then the type conversion incorrectly assumes that you've reached the end of the result set. This makes it difficult to work with the root object because it has an ID of 0.
- The C and Python implementations otherwise behave quite differently.

**Comment by jamadden** [comment]
The PyPy issue appears to be a JIT bug.

The underlying error is in connection.py: The value of the 'status_flag' in the OK result packet (`handle_ok`) is coming back with the `ServerFlag.MORE_RESULTS_EXIST` bit set, causing this error to be raised.

`protocol.py` has `parse_ok` that parses the `status_flag` from a packet like this:
```python
(ok_packet['status_flag'],
 ok_packet['warning_count']) = struct.unpack('<HH', packet[0:4])
```

I tweaked the error message to report the packet value, and to also unpack the data at that time. You can see I get two different results:

```python
 if self._have_next_result:
     from .catch23 import PY2, struct_unpack
     raise errors.InterfaceError(
         'Use cmd_query_iter for statements with multiple queries.\n%s\n%r\n%r\nUnpacks to:%r' % (
             query, result, raw_result, 
             struct_unpack('<HH', raw_result[0:4])))
```

```
    InterfaceError: Use cmd_query_iter for statements with multiple queries.
    INSERT INTO temp_pack_visit (zoid, keep_tid)
    SELECT zoid, 0
    FROM current_object
    WHERE tid > 274639514178723874
    {'field_count': 0, 'affected_rows': 0, 'insert_id': 0,
    'status_flag': 3480, 'warning_count': 0, 'info_msg': u'Records: 0  Duplicates: 0  Warnings: 0'}
    bytearray(b'.\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00&Records: 0  Duplicates: 0  Warnings: 0')
    Unpacks to:(46, 256)
```

You can see that protocol's `parse_ok` method gets a `status_flag` of `3480`, while performing the same unpacking on the same data in this function gets a value of `46` (which is what CPython gets too).

Most damningly, running with `--jit off` solves the problem.

**Comment by jamadden** [comment]
Filed: https://bitbucket.org/pypy/pypy/issues/3014/jit-issue-inlining-structunpack-hh
