### ISSUE TITLE
zodbpack on oracle db with pack-gc=true gives error

### ISSUE THREAD

**Issue by peterjacobs** [zodb/relstorage#30]
packing the ZODB gives an error when the setting **pack-gc=true** . It works fine when **pack-gc=false**

Relstorage versions working: 1.5.1 and 1.6.0b1
Relstorage versions not working: 1.6.0b2 and 1.6.0b3

database: Oracle11

```
bin/zodbpack bin/zodbpack.cfg                                                                        
2016-04-22 16:38:17,956 [zodbpack] INFO Opening storage (RelStorageFactory)...
2016-04-22 16:38:18,215 [zodbpack] INFO Packing storage (RelStorageFactory).
2016-04-22 16:38:18,314 [relstorage] INFO pack: analyzing transactions committed Fri Apr 22 16:24:57 2016 or before
2016-04-22 16:38:18,361 [relstorage.adapters.packundo] INFO pre_pack: start with gc enabled
2016-04-22 16:38:18,505 [relstorage.adapters.packundo] INFO analyzing references from objects in 8418 new transaction(s)
2016-04-22 16:38:18,513 [relstorage.adapters.packundo] ERROR pre_pack: failed
Traceback (most recent call last):
  File "/demo/eggs/RelStorage-1.6.0b2-py2.7.egg/relstorage/adapters/packundo.py", line 504, in pre_pack
    conn, cursor, pack_tid, get_references)
  File "/demo/eggs/RelStorage-1.6.0b2-py2.7.egg/relstorage/adapters/packundo.py", line 598, in _pre_pack_with_gc
    self.fill_object_refs(conn, cursor, get_references)
  File "/demo/eggs/RelStorage-1.6.0b2-py2.7.egg/relstorage/adapters/packundo.py", line 404, in fill_object_refs
    self._add_refs_for_tid(cursor, tid, get_references)
  File "/demo/eggs/RelStorage-1.6.0b2-py2.7.egg/relstorage/adapters/packundo.py", line 443, in _add_refs_for_tid
    state = state.read()
ProgrammingError: LOB variable no longer valid after subsequent fetch
```
zodbpack.cfg
```
<relstorage>
  pack-gc true
  <oracle>
    dsn  (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = host)(PORT = 1234)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = PLONE)))
    user plone
    password pwd
  </oracle>
</relstorage>
```

**Comment by peterjacobs** [comment]
as far a I understand, the bug was introduced with this commit: https://github.com/zodb/relstorage/commit/2df8f8df9a747e95bc7971fcea02845e677a04c0

from the cx_oracle documentation ( http://cx-oracle.readthedocs.org/en/latest/lob.html ) 

> Internally, Oracle uses LOB locators which are allocated based on the cursor array size. Thus, it is important that the data in the LOB object be manipulated before another internal fetch takes place. The safest way to do this is to use the cursor as an iterator. In particular, do not use the fetchall() method. The exception “LOB variable no longer valid after subsequent fetch” will be raised if an attempt to access a LOB variable after a subsequent fetch is detected.

**Comment by jamadden** [comment]
This bug is reproducible by the test suite.

**Comment by jamadden** [comment]
Fixed as part of #55 (because I had to be sure all tests pass under both Py2 and Py3).

**Comment by peterjacobs** [comment]
we have a history preserving ZODB on oracle (Plone 4) with RelStorage 1.6.2.
the backport fix for #30 doesn't work, even if I update "OracleHistoryPreservingPackUndo" the same way as "OracleHistoryFreePackUndo"  (add "_fetchmany = _oracle_fetchmany")

**Comment by jamadden** [comment]
@peterjacobs Can you open a new issue, and provide the traceback you're getting?

**Comment by peterjacobs** [comment]
done: #135
