### ISSUE TITLE
Cache MVCC Test Failures on AppVeyor

### ISSUE THREAD

**Issue by jamadden** [zodb/relstorage#347]
I've only observed this on AppVeyor, and only on MySQL. I've seen it twice so far, and it clears itself up on a second run. The tests in question suggest some sort of rare race condition.

```python traceback
Failure in test check7ZODBThreads (relstorage.tests.testmysql.MySQLHistoryFreeRelStorageTests_PyMySQL)
Traceback (most recent call last):
  File "C:\Python37-x64\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python37-x64\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 234, in check7ZODBThreads
    self._checkNThreads(7, ZODBClientThread, db, self)
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 222, in _checkNThreads
    t.join(60)
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 45, in join
    self._exc_info[0], self._exc_info[1], self._exc_info[2])
  File "C:\Python37-x64\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 37, in run
    self.runtest()
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 68, in runtest
    self.commit(d, i)
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 75, in commit
    transaction.commit()
  File "C:\Python37-x64\lib\site-packages\transaction\_manager.py", line 252, in commit
    return self.manager.commit()
  File "C:\Python37-x64\lib\site-packages\transaction\_manager.py", line 131, in commit
    return self.get().commit()
  File "C:\Python37-x64\lib\site-packages\transaction\_transaction.py", line 316, in commit
    self._synchronizers.map(lambda s: s.afterCompletion(self))
  File "C:\Python37-x64\lib\site-packages\transaction\weakset.py", line 61, in map
    f(elt)
  File "C:\Python37-x64\lib\site-packages\transaction\_transaction.py", line 316, in <lambda>
    self._synchronizers.map(lambda s: s.afterCompletion(self))
  File "C:\Python37-x64\lib\site-packages\ZODB\Connection.py", line 757, in afterCompletion
    self.newTransaction(transaction, False)
  File "C:\Python37-x64\lib\site-packages\ZODB\Connection.py", line 737, in newTransaction
    invalidated = self._storage.poll_invalidations()
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 617, in poll_invalidations
    self.__on_load_first_use
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 185, in restart_and_call
    return self.call(callback, True, *args, **kw)
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 214, in call
    return f(self.connection, self._cursor, fresh_connection, *args, **kwargs)
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 183, in callback
    return f(conn, cursor, *args, **kwargs)
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 715, in __on_load_first_use
    ignore_tid
  File "c:\projects\relstorage\src\relstorage\cache\storage_cache.py", line 584, in poll
    changes = self.polling_state.poll(self, conn, cursor)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 603, in poll
    return self._poll(cache, conn, cursor, cur_ix, cur_ix_hvt)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 734, in _poll
    change_iter
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 455, in with_polled_changes
    changes)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 98, in __init__
    self.verify()
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 112, in verify
    assert max_stored_tid <= hvt, (max_stored_tid, hvt, self)
AssertionError: (275423876718431591, 275423876718431590, <_TransactionRangeObjectIndex at 0x4527b72688 hvt=275423876718431590 complete_after=275423876717313827 len=4 readonly=False>)
```

```python traceback
Failure in test checkPackNowWhileWriting (relstorage.tests.testmysql.MySQLHistoryFreeRelStorageTests_PyMySQL)
Traceback (most recent call last):
  File "C:\Python37-x64\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Python37-x64\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\util.py", line 265, in wrapper
    return func(*args, **kwargs)
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\PackableStorage.py", line 284, in checkPackNowWhileWriting
    self._PackWhileWriting(pack_now=True)
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\PackableStorage.py", line 229, in _PackWhileWriting
    t.join(60)
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 45, in join
    self._exc_info[0], self._exc_info[1], self._exc_info[2])
  File "C:\Python37-x64\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 37, in run
    self.runtest()
  File "C:\Python37-x64\lib\site-packages\ZODB\tests\PackableStorage.py", line 766, in runtest
    transaction.commit()
  File "C:\Python37-x64\lib\site-packages\transaction\_manager.py", line 252, in commit
    return self.manager.commit()
  File "C:\Python37-x64\lib\site-packages\transaction\_manager.py", line 131, in commit
    return self.get().commit()
  File "C:\Python37-x64\lib\site-packages\transaction\_transaction.py", line 316, in commit
    self._synchronizers.map(lambda s: s.afterCompletion(self))
  File "C:\Python37-x64\lib\site-packages\transaction\weakset.py", line 61, in map
    f(elt)
  File "C:\Python37-x64\lib\site-packages\transaction\_transaction.py", line 316, in <lambda>
    self._synchronizers.map(lambda s: s.afterCompletion(self))
  File "C:\Python37-x64\lib\site-packages\ZODB\Connection.py", line 757, in afterCompletion
    self.newTransaction(transaction, False)
  File "C:\Python37-x64\lib\site-packages\ZODB\Connection.py", line 737, in newTransaction
    invalidated = self._storage.poll_invalidations()
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 617, in poll_invalidations
    self.__on_load_first_use
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 185, in restart_and_call
    return self.call(callback, True, *args, **kw)
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 214, in call
    return f(self.connection, self._cursor, fresh_connection, *args, **kwargs)
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 183, in callback
    return f(conn, cursor, *args, **kwargs)
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 715, in __on_load_first_use
    ignore_tid
  File "c:\projects\relstorage\src\relstorage\cache\storage_cache.py", line 584, in poll
    changes = self.polling_state.poll(self, conn, cursor)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 603, in poll
    return self._poll(cache, conn, cursor, cur_ix, cur_ix_hvt)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 703, in _poll
    change_iter
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 455, in with_polled_changes
    changes)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 98, in __init__
    self.verify()
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 112, in verify
    assert max_stored_tid <= hvt, (max_stored_tid, hvt, self)
AssertionError: (275423879281217179, 275423879281217178, <_TransactionRangeObjectIndex at 0x4527176ae8 hvt=275423879281217178 complete_after=275423879280096976 len=6 readonly=False>)
```

**Comment by jamadden** [comment]
In a production deployment, the AssertionError is caught and turned into a type of ConflictError that should transparently lead to a retry.

**Comment by jamadden** [comment]
Here it is on Python 2.7; I've also seen it on 3.5. It's only in these two concurrent tests. I still haven't observed it on Travis or been able to produce it locally.
```python traceback
Failure in test check7ZODBThreads (relstorage.tests.testmysql.MySQLHistoryFreeRelStorageTests_PyMySQL)
Traceback (most recent call last):
  File "C:\Python27-x64\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\Python27-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 234, in check7ZODBThreads
    self._checkNThreads(7, ZODBClientThread, db, self)
  File "C:\Python27-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 222, in _checkNThreads
    t.join(60)
  File "C:\Python27-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 45, in join
    self._exc_info[0], self._exc_info[1], self._exc_info[2])
  File "C:\Python27-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 37, in run
    self.runtest()
  File "C:\Python27-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 63, in runtest
    d = self.get_thread_dict(root)
  File "C:\Python27-x64\lib\site-packages\ZODB\tests\MTStorage.py", line 95, in get_thread_dict
    transaction.commit()
  File "C:\Python27-x64\lib\site-packages\transaction\_manager.py", line 252, in commit
    return self.manager.commit()
  File "C:\Python27-x64\lib\site-packages\transaction\_manager.py", line 131, in commit
    return self.get().commit()
  File "C:\Python27-x64\lib\site-packages\transaction\_transaction.py", line 311, in commit
    reraise(t, v, tb)
  File "C:\Python27-x64\lib\site-packages\transaction\_transaction.py", line 302, in commit
    self._commitResources()
  File "C:\Python27-x64\lib\site-packages\transaction\_transaction.py", line 446, in _commitResources
    self._synchronizers.map(lambda s: s.afterCompletion(self))
  File "C:\Python27-x64\lib\site-packages\transaction\weakset.py", line 61, in map
    f(elt)
  File "C:\Python27-x64\lib\site-packages\transaction\_transaction.py", line 446, in <lambda>
    self._synchronizers.map(lambda s: s.afterCompletion(self))
  File "C:\Python27-x64\lib\site-packages\ZODB\Connection.py", line 757, in afterCompletion
    self.newTransaction(transaction, False)
  File "C:\Python27-x64\lib\site-packages\ZODB\Connection.py", line 737, in newTransaction
    invalidated = self._storage.poll_invalidations()
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 630, in poll_invalidations
    self.__on_load_first_use
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 196, in restart_and_call
    return self.call(callback, True, *args, **kw)
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 225, in call
    return f(self.connection, self._cursor, fresh_connection, *args, **kwargs)
  File "c:\projects\relstorage\src\relstorage\adapters\connections.py", line 194, in callback
    return f(conn, cursor, *args, **kwargs)
  File "c:\projects\relstorage\src\relstorage\storage\__init__.py", line 728, in __on_load_first_use
    ignore_tid
  File "c:\projects\relstorage\src\relstorage\cache\storage_cache.py", line 563, in poll
    changes = self.polling_state.poll(self, conn, cursor)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 587, in poll
    return self._poll(cache, conn, cursor, cur_ix, cur_ix_hvt)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 718, in _poll
    change_iter
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 455, in with_polled_changes
    changes)
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 98, in __init__
    self.verify()
  File "c:\projects\relstorage\src\relstorage\cache\mvcc.py", line 112, in verify
    assert max_stored_tid <= hvt, (max_stored_tid, hvt, self)
AssertionError: (275503347081677636L, 275503347080559378L, <_TransactionRangeObjectIndex at 0x4b326d0 hvt=275503347080559378 complete_after=275503347080559377 len=2 readonly=False>)
```

**Comment by jamadden** [comment]
I've never observed this for PostegreSQL. On Windows, we default to the pure-Python PyMySQL for MySQL support, but use the native binary psycopg2 for PostgreSQL.
