### ISSUE TITLE
Fix packing on PostgreSQL 9.6

### ISSUE THREAD

**Issue by jamadden** [zodb/relstorage#93]
Packing works against 9.4 and 9.5, but against 9.6beta2, it always fails with an error like this:
```
======================================================================
ERROR: checkCreationUndoneGetTid (relstorage.tests.testpostgresql.HPPostgreSQLTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "//ZODB/tests/TransactionalUndoStorage.py", line 160, in checkCreationUndoneGetTid
    self._begin_undos_vote(t, tid)
  File "//ZODB/tests/TransactionalUndoStorage.py", line 105, in _begin_undos_vote
    undo_result = self._storage.undo(tid, t)
  File "//perfmetrics-2.0-py2.7.egg/perfmetrics/__init__.py", line 133, in call_with_metric
    return f(*args, **kw)
  File "relstorage/storage.py", line 1200, in undo
    adapter.locker.release_pack_lock(cursor)
  File "relstorage/adapters/locker.py", line 113, in release_pack_lock
    cursor.execute("SELECT pg_advisory_unlock(1)")
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

The server always logs a corresponding error (which we log as a WARNING):
```
ERROR:  no relation entry for relid 1
STATEMENT:  INSERT INTO object_state (zoid, tid, prev_tid, md5, state_size, state)
	SELECT temp_undo.zoid, 268026966490786218, current_object.tid,
	md5, COALESCE(state_size, 0), state
	FROM temp_undo
	JOIN current_object ON (temp_undo.zoid = current_object.zoid)
	LEFT JOIN object_state
	ON (object_state.zoid = temp_undo.zoid
	AND object_state.tid = temp_undo.prev_tid)
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:  SELECT pg_advisory_unlock(1)
```

This could be a beta issue, but I didn't notice anything in the release notes about it.

**Comment by jamadden** [comment]
Some googling suggests this is a PostgreSQL internal error.

**Comment by jamadden** [comment]
PostgreSQL 9.6B3 has been released. Just waiting for my packaging system (macports) to catch up for testing.

**Comment by jamadden** [comment]
The tests are clean with Postgre 9.6rc1.
